export const INCREMENT_COUNTER = 'INCREMENT_COUNTER';
export const CREATE_ACCOUNT_STARTING = 'CREATE_ACCOUNT_STARTING';
export const CREATE_ACCOUNT_STARTED = 'CREATE_ACCOUNT_STARTED';
export const CREATE_ACCOUNT_COMPLETED = 'CREATE_ACCOUNT_COMPLETED';
export const UPDATE_ACCOUNT_STARTING = 'UPDATE_ACCOUNT_STARTING';
export const UPDATE_ACCOUNT_STARTED = 'UPDATE_ACCOUNT_STARTED';
export const UPDATE_ACCOUNT_COMPLETED = 'UPDATE_ACCOUNT_COMPLETED';
export const DELETE_ACCOUNT_STARTING = 'DELETE_ACCOUNT_STARTING';
export const DELETE_ACCOUNT_STARTED = 'DELETE_ACCOUNT_STARTED';
export const DELETE_ACCOUNT_COMPLETED = 'DELETE_ACCOUNT_COMPLETED';
export const LIST_ACCOUNT_STARTING = 'LIST_ACCOUNT_STARTING';
export const LIST_ACCOUNT_STARTED = 'LIST_ACCOUNT_STARTED';
export const LIST_ACCOUNT_COMPLETED = 'LIST_ACCOUNT_COMPLETED';


export const CREATE_ASSET_STARTING = 'CREATE_ASSET_STARTING';
export const CREATE_ASSET_STARTED = 'CREATE_ASSET_STARTED';
export const CREATE_ASSET_COMPLETED = 'CREATE_ASSET_COMPLETED';
export const UPDATE_ASSET_STARTING = 'UPDATE_ASSET_STARTING';
export const UPDATE_ASSET_STARTED = 'UPDATE_ASSET_STARTED';
export const UPDATE_ASSET_COMPLETED = 'UPDATE_ASSET_COMPLETED';
export const DELETE_ASSET_STARTING = 'DELETE_ASSET_STARTING';
export const DELETE_ASSET_STARTED = 'DELETE_ASSET_STARTED';
export const DELETE_ASSET_COMPLETED = 'DELETE_ASSET_COMPLETED';
export const LIST_ASSET_STARTING = 'LIST_ASSET_STARTING';
export const LIST_ASSET_STARTED = 'LIST_ASSET_STARTED';
export const LIST_ASSET_COMPLETED = 'LIST_ASSET_COMPLETED';


export const CREATE_MANAGE_ASSET_STARTING = 'CREATE_MANAGE_ASSET_STARTING';
export const CREATE_MANAGE_ASSET_STARTED = 'CREATE_MANAGE_ASSET_STARTED';
export const CREATE_MANAGE_ASSET_COMPLETED = 'CREATE_MANAGE_ASSET_COMPLETED';
export const UPDATE_MANAGE_ASSET_STARTING = 'UPDATE_MANAGE_ASSET_STARTING';
export const UPDATE_MANAGE_ASSET_STARTED = 'UPDATE_MANAGE_ASSET_STARTED';
export const UPDATE_MANAGE_ASSET_COMPLETED = 'UPDATE_MANAGE_ASSET_COMPLETED';
export const DELETE_MANAGE_ASSET_STARTING = 'DELETE_MANAGE_ASSET_STARTING';
export const DELETE_MANAGE_ASSET_STARTED = 'DELETE_MANAGE_ASSET_STARTED';
export const DELETE_MANAGE_ASSET_COMPLETED = 'DELETE_MANAGE_ASSET_COMPLETED';
export const LIST_MANAGE_ASSET_STARTING = 'LIST_MANAGE_ASSET_STARTING';
export const LIST_MANAGE_ASSET_STARTED = 'LIST_MANAGE_ASSET_STARTED';
export const LIST_MANAGE_ASSET_COMPLETED = 'LIST_MANAGE_ASSET_COMPLETED';