export const CREATE_ACCOUNT_STARTING = 'CREATE_ACCOUNT_STARTING';
export const CREATE_ACCOUNT_STARTED = 'CREATE_ACCOUNT_STARTED';
export const CREATE_ACCOUNT_COMPLETED = 'CREATE_ACCOUNT_COMPLETED';
export const UPDATE_ACCOUNT_STARTING = 'UPDATE_ACCOUNT_STARTING';
export const UPDATE_ACCOUNT_STARTED = 'UPDATE_ACCOUNT_STARTED';
export const UPDATE_ACCOUNT_COMPLETED = 'UPDATE_ACCOUNT_COMPLETED';
export const DELETE_ACCOUNT_STARTING = 'DELETE_ACCOUNT_STARTING';
export const DELETE_ACCOUNT_STARTED = 'DELETE_ACCOUNT_STARTED';
export const DELETE_ACCOUNT_COMPLETED = 'DELETE_ACCOUNT_COMPLETED';
export const LIST_ACCOUNT_STARTING = 'LIST_ACCOUNT_STARTING';
export const LIST_ACCOUNT_STARTED = 'LIST_ACCOUNT_STARTED';
export const LIST_ACCOUNT_COMPLETED = 'LIST_ACCOUNT_COMPLETED';
export const VIEW_ACCOUNT_STARTING = 'VIEW_ACCOUNT_STARTING';
export const VIEW_ACCOUNT_STARTED = 'VIEW_ACCOUNT_STARTED';
export const VIEW_ACCOUNT_COMPLETED = 'VIEW_ACCOUNT_COMPLETED';

export const LIST_ACCOUNT_ERROR = 'LIST_ACCOUNT_ERROR';
