export const CREATE_MANAGE_ASSET_STARTING = 'CREATE_MANAGE_ASSET_STARTING';
export const CREATE_MANAGE_ASSET_STARTED = 'CREATE_MANAGE_ASSET_STARTED';
export const CREATE_MANAGE_ASSET_COMPLETED = 'CREATE_MANAGE_ASSET_COMPLETED';
export const UPDATE_MANAGE_ASSET_STARTING = 'UPDATE_MANAGE_ASSET_STARTING';
export const UPDATE_MANAGE_ASSET_STARTED = 'UPDATE_MANAGE_ASSET_STARTED';
export const UPDATE_MANAGE_ASSET_COMPLETED = 'UPDATE_MANAGE_ASSET_COMPLETED';
export const DELETE_MANAGE_ASSET_STARTING = 'DELETE_MANAGE_ASSET_STARTING';
export const DELETE_MANAGE_ASSET_STARTED = 'DELETE_MANAGE_ASSET_STARTED';
export const DELETE_MANAGE_ASSET_COMPLETED = 'DELETE_MANAGE_ASSET_COMPLETED';
export const LIST_MANAGE_ASSET_STARTING = 'LIST_MANAGE_ASSET_STARTING';
export const LIST_MANAGE_ASSET_STARTED = 'LIST_MANAGE_ASSET_STARTED';
export const LIST_MANAGE_ASSET_COMPLETED = 'LIST_MANAGE_ASSET_COMPLETED';
export const VIEW_MANAGE_ASSET_STARTING = 'VIEW_MANAGE_ASSET_STARTING';
export const VIEW_MANAGE_ASSET_STARTED = 'VIEW_MANAGE_ASSET_STARTED';
export const VIEW_MANAGE_ASSET_COMPLETED = 'VIEW_MANAGE_ASSET_COMPLETED';

export const LIST_MANAGE_ASSET_ERROR = 'LIST_MANAGE_ASSET_ERROR';
